### ISSUE TITLE
Running in folder that does not contain package.json gives unhelpful error message

### ISSUE THREAD

**Issue by feross** [feross/thanks#69]
Originally reported here: https://github.com/feross/thanks/pull/50#issuecomment-366233280

```
✖ Error: path must be a string or Buffer

Found a bug? Open an issue at https://github.com/feross/thanks

TypeError: path must be a string or Buffer
    at fs.readFile (fs.js:358:11)
    at P (/Users/feross/code/thanks/node_modules/pify/index.js:49:6)
    at new Promise (<anonymous>)
    at /Users/feross/code/thanks/node_modules/pify/index.js:11:9
    at ret (/Users/feross/code/thanks/node_modules/pify/index.js:72:32)
    at readDirectPkgNames (/Users/feross/code/thanks/src/cmd.js:392:24)
    at <anonymous>

```

**Comment by feross** [comment]
1.5.1
